
services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init/:/docker-entrypoint-initdb.d
      - ./db/config/:/etc/mysql/conf.d

  kafka:
    image: debezium/kafka:3.0
    environment:
      NODE_ID: 1
      CLUSTER_ID: oh-sxaDRTcyAr6pFRbXyzA'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/kafka/data
      - kafka_logs:/kafka/logs

  debezium-connect:
    image: debezium/connect:3.0
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - 8083:8083
    links:
      - kafka
      - db
      - elasticsearch
    volumes:
      - ./connectors/elasticsearch-connector:/kafka/connect/elasticsearch-connector
    
  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  
  kibana:
    image: kibana:8.14.3
    container_name: kibana
    links:
     - elasticsearch
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  db_data:
  kafka_data:
  kafka_logs:
  elasticsearch_data: